/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Answer Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.AnswerEvent#getEvName <em>Ev Name</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getAnswerEvent()
 * @model
 * @generated
 */
public interface AnswerEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Ev Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ev Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ev Name</em>' attribute.
   * @see #setEvName(String)
   * @see xtext.qactor.qADocker.QADockerPackage#getAnswerEvent_EvName()
   * @model
   * @generated
   */
  String getEvName();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.AnswerEvent#getEvName <em>Ev Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ev Name</em>' attribute.
   * @see #getEvName()
   * @generated
   */
  void setEvName(String value);

} // AnswerEvent
