/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Robot Move</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getBasicRobotMove()
 * @model
 * @generated
 */
public interface BasicRobotMove extends Move
{
} // BasicRobotMove
