/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delay</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getDelay()
 * @model
 * @generated
 */
public interface Delay extends ExtensionMove
{
} // Delay
