/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends OutOnlyMessage
{
} // Event
