/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Guard Predicate Stable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getGuardPredicateStable()
 * @model
 * @generated
 */
public interface GuardPredicateStable extends GuardPredicate
{
} // GuardPredicateStable
