/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invitation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getInvitation()
 * @model
 * @generated
 */
public interface Invitation extends OutInMessage
{
} // Invitation
