/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memo Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getMemoEvent()
 * @model
 * @generated
 */
public interface MemoEvent extends MemoRule
{
} // MemoEvent
