/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.NormalEvent#getEv <em>Ev</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.NormalEvent#getPlanRef <em>Plan Ref</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getNormalEvent()
 * @model
 * @generated
 */
public interface NormalEvent extends AlarmEvent
{
  /**
   * Returns the value of the '<em><b>Ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ev</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ev</em>' reference.
   * @see #setEv(Event)
   * @see xtext.qactor.qADocker.QADockerPackage#getNormalEvent_Ev()
   * @model
   * @generated
   */
  Event getEv();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.NormalEvent#getEv <em>Ev</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ev</em>' reference.
   * @see #getEv()
   * @generated
   */
  void setEv(Event value);

  /**
   * Returns the value of the '<em><b>Plan Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plan Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan Ref</em>' reference.
   * @see #setPlanRef(Plan)
   * @see xtext.qactor.qADocker.QADockerPackage#getNormalEvent_PlanRef()
   * @model
   * @generated
   */
  Plan getPlanRef();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.NormalEvent#getPlanRef <em>Plan Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan Ref</em>' reference.
   * @see #getPlanRef()
   * @generated
   */
  void setPlanRef(Plan value);

} // NormalEvent
