/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom Cut</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getPAtomCut()
 * @model
 * @generated
 */
public interface PAtomCut extends PPredef
{
} // PAtomCut
