/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.Plan#getName <em>Name</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.Plan#isNormal <em>Normal</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.Plan#isResume <em>Resume</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.Plan#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getPlan()
 * @model
 * @generated
 */
public interface Plan extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.qactor.qADocker.QADockerPackage#getPlan_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.Plan#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Normal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Normal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Normal</em>' attribute.
   * @see #setNormal(boolean)
   * @see xtext.qactor.qADocker.QADockerPackage#getPlan_Normal()
   * @model
   * @generated
   */
  boolean isNormal();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.Plan#isNormal <em>Normal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Normal</em>' attribute.
   * @see #isNormal()
   * @generated
   */
  void setNormal(boolean value);

  /**
   * Returns the value of the '<em><b>Resume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resume</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resume</em>' attribute.
   * @see #setResume(boolean)
   * @see xtext.qactor.qADocker.QADockerPackage#getPlan_Resume()
   * @model
   * @generated
   */
  boolean isResume();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.Plan#isResume <em>Resume</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resume</em>' attribute.
   * @see #isResume()
   * @generated
   */
  void setResume(boolean value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference list.
   * The list contents are of type {@link xtext.qactor.qADocker.PlanAction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference list.
   * @see xtext.qactor.qADocker.QADockerPackage#getPlan_Action()
   * @model containment="true"
   * @generated
   */
  EList<PlanAction> getAction();

} // Plan
