/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>QActor System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.QActorSystem#getSpec <em>Spec</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getQActorSystem()
 * @model
 * @generated
 */
public interface QActorSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Spec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec</em>' containment reference.
   * @see #setSpec(QActorSystemSpec)
   * @see xtext.qactor.qADocker.QADockerPackage#getQActorSystem_Spec()
   * @model containment="true"
   * @generated
   */
  QActorSystemSpec getSpec();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.QActorSystem#getSpec <em>Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spec</em>' containment reference.
   * @see #getSpec()
   * @generated
   */
  void setSpec(QActorSystemSpec value);

} // QActorSystem
