/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xtext.qactor.qADocker.QADockerPackage
 * @generated
 */
public interface QADockerFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QADockerFactory eINSTANCE = xtext.qactor.qADocker.impl.QADockerFactoryImpl.init();

  /**
   * Returns a new object of class '<em>QActor System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QActor System</em>'.
   * @generated
   */
  QActorSystem createQActorSystem();

  /**
   * Returns a new object of class '<em>QActor System Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QActor System Spec</em>'.
   * @generated
   */
  QActorSystemSpec createQActorSystemSpec();

  /**
   * Returns a new object of class '<em>Robot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Robot</em>'.
   * @generated
   */
  Robot createRobot();

  /**
   * Returns a new object of class '<em>Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message</em>'.
   * @generated
   */
  Message createMessage();

  /**
   * Returns a new object of class '<em>Out Only Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Out Only Message</em>'.
   * @generated
   */
  OutOnlyMessage createOutOnlyMessage();

  /**
   * Returns a new object of class '<em>Out In Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Out In Message</em>'.
   * @generated
   */
  OutInMessage createOutInMessage();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>Signal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signal</em>'.
   * @generated
   */
  Signal createSignal();

  /**
   * Returns a new object of class '<em>Token</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Token</em>'.
   * @generated
   */
  Token createToken();

  /**
   * Returns a new object of class '<em>Dispatch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dispatch</em>'.
   * @generated
   */
  Dispatch createDispatch();

  /**
   * Returns a new object of class '<em>Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Request</em>'.
   * @generated
   */
  Request createRequest();

  /**
   * Returns a new object of class '<em>Invitation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invitation</em>'.
   * @generated
   */
  Invitation createInvitation();

  /**
   * Returns a new object of class '<em>Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Context</em>'.
   * @generated
   */
  Context createContext();

  /**
   * Returns a new object of class '<em>QActor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QActor</em>'.
   * @generated
   */
  QActor createQActor();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>PHead</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PHead</em>'.
   * @generated
   */
  PHead createPHead();

  /**
   * Returns a new object of class '<em>PTerm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PTerm</em>'.
   * @generated
   */
  PTerm createPTerm();

  /**
   * Returns a new object of class '<em>PAtom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAtom</em>'.
   * @generated
   */
  PAtom createPAtom();

  /**
   * Returns a new object of class '<em>PAtom String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAtom String</em>'.
   * @generated
   */
  PAtomString createPAtomString();

  /**
   * Returns a new object of class '<em>PAtomic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAtomic</em>'.
   * @generated
   */
  PAtomic createPAtomic();

  /**
   * Returns a new object of class '<em>PAtom Num</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAtom Num</em>'.
   * @generated
   */
  PAtomNum createPAtomNum();

  /**
   * Returns a new object of class '<em>PStruct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PStruct</em>'.
   * @generated
   */
  PStruct createPStruct();

  /**
   * Returns a new object of class '<em>PActor Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PActor Call</em>'.
   * @generated
   */
  PActorCall createPActorCall();

  /**
   * Returns a new object of class '<em>PPredef</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PPredef</em>'.
   * @generated
   */
  PPredef createPPredef();

  /**
   * Returns a new object of class '<em>PIs</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PIs</em>'.
   * @generated
   */
  PIs createPIs();

  /**
   * Returns a new object of class '<em>PAtom Cut</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PAtom Cut</em>'.
   * @generated
   */
  PAtomCut createPAtomCut();

  /**
   * Returns a new object of class '<em>Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data</em>'.
   * @generated
   */
  Data createData();

  /**
   * Returns a new object of class '<em>Integer Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Data</em>'.
   * @generated
   */
  IntegerData createIntegerData();

  /**
   * Returns a new object of class '<em>String Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Data</em>'.
   * @generated
   */
  StringData createStringData();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plan</em>'.
   * @generated
   */
  Plan createPlan();

  /**
   * Returns a new object of class '<em>Plan Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plan Action</em>'.
   * @generated
   */
  PlanAction createPlanAction();

  /**
   * Returns a new object of class '<em>Guard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guard</em>'.
   * @generated
   */
  Guard createGuard();

  /**
   * Returns a new object of class '<em>Guard Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guard Predicate</em>'.
   * @generated
   */
  GuardPredicate createGuardPredicate();

  /**
   * Returns a new object of class '<em>Guard Predicate Removable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guard Predicate Removable</em>'.
   * @generated
   */
  GuardPredicateRemovable createGuardPredicateRemovable();

  /**
   * Returns a new object of class '<em>Guard Predicate Stable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guard Predicate Stable</em>'.
   * @generated
   */
  GuardPredicateStable createGuardPredicateStable();

  /**
   * Returns a new object of class '<em>Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move</em>'.
   * @generated
   */
  Move createMove();

  /**
   * Returns a new object of class '<em>Action Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Move</em>'.
   * @generated
   */
  ActionMove createActionMove();

  /**
   * Returns a new object of class '<em>Execute Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Execute Action</em>'.
   * @generated
   */
  ExecuteAction createExecuteAction();

  /**
   * Returns a new object of class '<em>Solve Goal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Solve Goal</em>'.
   * @generated
   */
  SolveGoal createSolveGoal();

  /**
   * Returns a new object of class '<em>Demo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Demo</em>'.
   * @generated
   */
  Demo createDemo();

  /**
   * Returns a new object of class '<em>Actor Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actor Op</em>'.
   * @generated
   */
  ActorOp createActorOp();

  /**
   * Returns a new object of class '<em>Basic Robot Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Robot Move</em>'.
   * @generated
   */
  BasicRobotMove createBasicRobotMove();

  /**
   * Returns a new object of class '<em>Basic Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Basic Move</em>'.
   * @generated
   */
  BasicMove createBasicMove();

  /**
   * Returns a new object of class '<em>Print</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print</em>'.
   * @generated
   */
  Print createPrint();

  /**
   * Returns a new object of class '<em>Print Current Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Current Event</em>'.
   * @generated
   */
  PrintCurrentEvent createPrintCurrentEvent();

  /**
   * Returns a new object of class '<em>Print Current Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Current Message</em>'.
   * @generated
   */
  PrintCurrentMessage createPrintCurrentMessage();

  /**
   * Returns a new object of class '<em>Memo Current Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memo Current Event</em>'.
   * @generated
   */
  MemoCurrentEvent createMemoCurrentEvent();

  /**
   * Returns a new object of class '<em>Memo Current Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memo Current Message</em>'.
   * @generated
   */
  MemoCurrentMessage createMemoCurrentMessage();

  /**
   * Returns a new object of class '<em>Plan Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plan Move</em>'.
   * @generated
   */
  PlanMove createPlanMove();

  /**
   * Returns a new object of class '<em>Get Activation Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Get Activation Event</em>'.
   * @generated
   */
  GetActivationEvent createGetActivationEvent();

  /**
   * Returns a new object of class '<em>Get Sensed Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Get Sensed Event</em>'.
   * @generated
   */
  GetSensedEvent createGetSensedEvent();

  /**
   * Returns a new object of class '<em>Load Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load Plan</em>'.
   * @generated
   */
  LoadPlan createLoadPlan();

  /**
   * Returns a new object of class '<em>Run Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Run Plan</em>'.
   * @generated
   */
  RunPlan createRunPlan();

  /**
   * Returns a new object of class '<em>Resume Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resume Plan</em>'.
   * @generated
   */
  ResumePlan createResumePlan();

  /**
   * Returns a new object of class '<em>Suspend Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Suspend Plan</em>'.
   * @generated
   */
  SuspendPlan createSuspendPlan();

  /**
   * Returns a new object of class '<em>Repeat Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repeat Plan</em>'.
   * @generated
   */
  RepeatPlan createRepeatPlan();

  /**
   * Returns a new object of class '<em>Switch Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Switch Plan</em>'.
   * @generated
   */
  SwitchPlan createSwitchPlan();

  /**
   * Returns a new object of class '<em>End Plan</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Plan</em>'.
   * @generated
   */
  EndPlan createEndPlan();

  /**
   * Returns a new object of class '<em>End Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Actor</em>'.
   * @generated
   */
  EndActor createEndActor();

  /**
   * Returns a new object of class '<em>Guard Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guard Move</em>'.
   * @generated
   */
  GuardMove createGuardMove();

  /**
   * Returns a new object of class '<em>Add Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Rule</em>'.
   * @generated
   */
  AddRule createAddRule();

  /**
   * Returns a new object of class '<em>Remove Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remove Rule</em>'.
   * @generated
   */
  RemoveRule createRemoveRule();

  /**
   * Returns a new object of class '<em>Message Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message Move</em>'.
   * @generated
   */
  MessageMove createMessageMove();

  /**
   * Returns a new object of class '<em>Send Dispatch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Dispatch</em>'.
   * @generated
   */
  SendDispatch createSendDispatch();

  /**
   * Returns a new object of class '<em>Send Request</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Request</em>'.
   * @generated
   */
  SendRequest createSendRequest();

  /**
   * Returns a new object of class '<em>Reply To Caller</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reply To Caller</em>'.
   * @generated
   */
  ReplyToCaller createReplyToCaller();

  /**
   * Returns a new object of class '<em>Receive Msg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Receive Msg</em>'.
   * @generated
   */
  ReceiveMsg createReceiveMsg();

  /**
   * Returns a new object of class '<em>Msg Spec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Msg Spec</em>'.
   * @generated
   */
  MsgSpec createMsgSpec();

  /**
   * Returns a new object of class '<em>On Receive Msg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>On Receive Msg</em>'.
   * @generated
   */
  OnReceiveMsg createOnReceiveMsg();

  /**
   * Returns a new object of class '<em>Msg Select</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Msg Select</em>'.
   * @generated
   */
  MsgSelect createMsgSelect();

  /**
   * Returns a new object of class '<em>Raise Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Raise Event</em>'.
   * @generated
   */
  RaiseEvent createRaiseEvent();

  /**
   * Returns a new object of class '<em>Sense Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sense Event</em>'.
   * @generated
   */
  SenseEvent createSenseEvent();

  /**
   * Returns a new object of class '<em>Msg Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Msg Switch</em>'.
   * @generated
   */
  MsgSwitch createMsgSwitch();

  /**
   * Returns a new object of class '<em>Event Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Switch</em>'.
   * @generated
   */
  EventSwitch createEventSwitch();

  /**
   * Returns a new object of class '<em>Continuation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Continuation</em>'.
   * @generated
   */
  Continuation createContinuation();

  /**
   * Returns a new object of class '<em>Extension Move</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extension Move</em>'.
   * @generated
   */
  ExtensionMove createExtensionMove();

  /**
   * Returns a new object of class '<em>Photo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Photo</em>'.
   * @generated
   */
  Photo createPhoto();

  /**
   * Returns a new object of class '<em>Sound</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sound</em>'.
   * @generated
   */
  Sound createSound();

  /**
   * Returns a new object of class '<em>Video</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video</em>'.
   * @generated
   */
  Video createVideo();

  /**
   * Returns a new object of class '<em>Delay</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delay</em>'.
   * @generated
   */
  Delay createDelay();

  /**
   * Returns a new object of class '<em>Answer Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Answer Event</em>'.
   * @generated
   */
  AnswerEvent createAnswerEvent();

  /**
   * Returns a new object of class '<em>Event Handler</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Handler</em>'.
   * @generated
   */
  EventHandler createEventHandler();

  /**
   * Returns a new object of class '<em>Event Handler Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Handler Body</em>'.
   * @generated
   */
  EventHandlerBody createEventHandlerBody();

  /**
   * Returns a new object of class '<em>Event Handler Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Handler Operation</em>'.
   * @generated
   */
  EventHandlerOperation createEventHandlerOperation();

  /**
   * Returns a new object of class '<em>Memo Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memo Operation</em>'.
   * @generated
   */
  MemoOperation createMemoOperation();

  /**
   * Returns a new object of class '<em>Solve Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Solve Operation</em>'.
   * @generated
   */
  SolveOperation createSolveOperation();

  /**
   * Returns a new object of class '<em>Send Event As Dispatch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Event As Dispatch</em>'.
   * @generated
   */
  SendEventAsDispatch createSendEventAsDispatch();

  /**
   * Returns a new object of class '<em>Memo Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memo Rule</em>'.
   * @generated
   */
  MemoRule createMemoRule();

  /**
   * Returns a new object of class '<em>Memo Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memo Event</em>'.
   * @generated
   */
  MemoEvent createMemoEvent();

  /**
   * Returns a new object of class '<em>Reaction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction</em>'.
   * @generated
   */
  Reaction createReaction();

  /**
   * Returns a new object of class '<em>Alarm Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alarm Event</em>'.
   * @generated
   */
  AlarmEvent createAlarmEvent();

  /**
   * Returns a new object of class '<em>Normal Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normal Event</em>'.
   * @generated
   */
  NormalEvent createNormalEvent();

  /**
   * Returns a new object of class '<em>Continue Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Continue Event</em>'.
   * @generated
   */
  ContinueEvent createContinueEvent();

  /**
   * Returns a new object of class '<em>Var Or Qactor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or Qactor</em>'.
   * @generated
   */
  VarOrQactor createVarOrQactor();

  /**
   * Returns a new object of class '<em>Var Or Int</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or Int</em>'.
   * @generated
   */
  VarOrInt createVarOrInt();

  /**
   * Returns a new object of class '<em>Var Or Atomic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or Atomic</em>'.
   * @generated
   */
  VarOrAtomic createVarOrAtomic();

  /**
   * Returns a new object of class '<em>Var Or String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or String</em>'.
   * @generated
   */
  VarOrString createVarOrString();

  /**
   * Returns a new object of class '<em>Var Or PStruct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or PStruct</em>'.
   * @generated
   */
  VarOrPStruct createVarOrPStruct();

  /**
   * Returns a new object of class '<em>Var Or Phead</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or Phead</em>'.
   * @generated
   */
  VarOrPhead createVarOrPhead();

  /**
   * Returns a new object of class '<em>Var Or Atom Or PStruct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Or Atom Or PStruct</em>'.
   * @generated
   */
  VarOrAtomOrPStruct createVarOrAtomOrPStruct();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>Time Limit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time Limit</em>'.
   * @generated
   */
  TimeLimit createTimeLimit();

  /**
   * Returns a new object of class '<em>Component IP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component IP</em>'.
   * @generated
   */
  ComponentIP createComponentIP();

  /**
   * Returns a new object of class '<em>Move File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move File</em>'.
   * @generated
   */
  MoveFile createMoveFile();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  QADockerPackage getQADockerPackage();

} //QADockerFactory
