/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Plan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.RunPlan#getPlainid <em>Plainid</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.RunPlan#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getRunPlan()
 * @model
 * @generated
 */
public interface RunPlan extends PlanMove
{
  /**
   * Returns the value of the '<em><b>Plainid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plainid</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plainid</em>' containment reference.
   * @see #setPlainid(VarOrAtomic)
   * @see xtext.qactor.qADocker.QADockerPackage#getRunPlan_Plainid()
   * @model containment="true"
   * @generated
   */
  VarOrAtomic getPlainid();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.RunPlan#getPlainid <em>Plainid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plainid</em>' containment reference.
   * @see #getPlainid()
   * @generated
   */
  void setPlainid(VarOrAtomic value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(TimeLimit)
   * @see xtext.qactor.qADocker.QADockerPackage#getRunPlan_Duration()
   * @model containment="true"
   * @generated
   */
  TimeLimit getDuration();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.RunPlan#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(TimeLimit value);

} // RunPlan
