/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sense Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.SenseEvent#getDuration <em>Duration</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.SenseEvent#getEvents <em>Events</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.SenseEvent#getPlans <em>Plans</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getSenseEvent()
 * @model
 * @generated
 */
public interface SenseEvent extends MessageMove
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(TimeLimit)
   * @see xtext.qactor.qADocker.QADockerPackage#getSenseEvent_Duration()
   * @model containment="true"
   * @generated
   */
  TimeLimit getDuration();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.SenseEvent#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(TimeLimit value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' reference list.
   * The list contents are of type {@link xtext.qactor.qADocker.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Events</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' reference list.
   * @see xtext.qactor.qADocker.QADockerPackage#getSenseEvent_Events()
   * @model
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Plans</b></em>' containment reference list.
   * The list contents are of type {@link xtext.qactor.qADocker.Continuation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plans</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plans</em>' containment reference list.
   * @see xtext.qactor.qADocker.QADockerPackage#getSenseEvent_Plans()
   * @model containment="true"
   * @generated
   */
  EList<Continuation> getPlans();

} // SenseEvent
