/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Plan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.SwitchPlan#getPlan <em>Plan</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getSwitchPlan()
 * @model
 * @generated
 */
public interface SwitchPlan extends PlanMove
{
  /**
   * Returns the value of the '<em><b>Plan</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plan</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plan</em>' reference.
   * @see #setPlan(Plan)
   * @see xtext.qactor.qADocker.QADockerPackage#getSwitchPlan_Plan()
   * @model
   * @generated
   */
  Plan getPlan();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.SwitchPlan#getPlan <em>Plan</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plan</em>' reference.
   * @see #getPlan()
   * @generated
   */
  void setPlan(Plan value);

} // SwitchPlan
