/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Or Atom Or PStruct</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getVar <em>Var</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getPsrtuct <em>Psrtuct</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getAtom <em>Atom</em>}</li>
 * </ul>
 *
 * @see xtext.qactor.qADocker.QADockerPackage#getVarOrAtomOrPStruct()
 * @model
 * @generated
 */
public interface VarOrAtomOrPStruct extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Variable)
   * @see xtext.qactor.qADocker.QADockerPackage#getVarOrAtomOrPStruct_Var()
   * @model containment="true"
   * @generated
   */
  Variable getVar();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variable value);

  /**
   * Returns the value of the '<em><b>Psrtuct</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Psrtuct</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Psrtuct</em>' containment reference.
   * @see #setPsrtuct(PStruct)
   * @see xtext.qactor.qADocker.QADockerPackage#getVarOrAtomOrPStruct_Psrtuct()
   * @model containment="true"
   * @generated
   */
  PStruct getPsrtuct();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getPsrtuct <em>Psrtuct</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Psrtuct</em>' containment reference.
   * @see #getPsrtuct()
   * @generated
   */
  void setPsrtuct(PStruct value);

  /**
   * Returns the value of the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atom</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atom</em>' containment reference.
   * @see #setAtom(PAtomic)
   * @see xtext.qactor.qADocker.QADockerPackage#getVarOrAtomOrPStruct_Atom()
   * @model containment="true"
   * @generated
   */
  PAtomic getAtom();

  /**
   * Sets the value of the '{@link xtext.qactor.qADocker.VarOrAtomOrPStruct#getAtom <em>Atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atom</em>' containment reference.
   * @see #getAtom()
   * @generated
   */
  void setAtom(PAtomic value);

} // VarOrAtomOrPStruct
