/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Window Color</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see xtext.qactor.qADocker.QADockerPackage#getWindowColor()
 * @model
 * @generated
 */
public enum WindowColor implements Enumerator
{
  /**
   * The '<em><b>White</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WHITE_VALUE
   * @generated
   * @ordered
   */
  WHITE(0, "white", "white"),

  /**
   * The '<em><b>Gray</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GRAY_VALUE
   * @generated
   * @ordered
   */
  GRAY(1, "gray", "gray"),

  /**
   * The '<em><b>Blue</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLUE_VALUE
   * @generated
   * @ordered
   */
  BLUE(2, "blue", "blue"),

  /**
   * The '<em><b>Green</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREEN_VALUE
   * @generated
   * @ordered
   */
  GREEN(3, "green", "green"),

  /**
   * The '<em><b>Yellow</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YELLOW_VALUE
   * @generated
   * @ordered
   */
  YELLOW(4, "yellow", "yellow"),

  /**
   * The '<em><b>Cyan</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CYAN_VALUE
   * @generated
   * @ordered
   */
  CYAN(5, "cyan", "cyan");

  /**
   * The '<em><b>White</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>White</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WHITE
   * @model name="white"
   * @generated
   * @ordered
   */
  public static final int WHITE_VALUE = 0;

  /**
   * The '<em><b>Gray</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Gray</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GRAY
   * @model name="gray"
   * @generated
   * @ordered
   */
  public static final int GRAY_VALUE = 1;

  /**
   * The '<em><b>Blue</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Blue</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BLUE
   * @model name="blue"
   * @generated
   * @ordered
   */
  public static final int BLUE_VALUE = 2;

  /**
   * The '<em><b>Green</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Green</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GREEN
   * @model name="green"
   * @generated
   * @ordered
   */
  public static final int GREEN_VALUE = 3;

  /**
   * The '<em><b>Yellow</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Yellow</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #YELLOW
   * @model name="yellow"
   * @generated
   * @ordered
   */
  public static final int YELLOW_VALUE = 4;

  /**
   * The '<em><b>Cyan</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Cyan</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CYAN
   * @model name="cyan"
   * @generated
   * @ordered
   */
  public static final int CYAN_VALUE = 5;

  /**
   * An array of all the '<em><b>Window Color</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final WindowColor[] VALUES_ARRAY =
    new WindowColor[]
    {
      WHITE,
      GRAY,
      BLUE,
      GREEN,
      YELLOW,
      CYAN,
    };

  /**
   * A public read-only list of all the '<em><b>Window Color</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<WindowColor> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Window Color</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WindowColor get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      WindowColor result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Window Color</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WindowColor getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      WindowColor result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Window Color</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static WindowColor get(int value)
  {
    switch (value)
    {
      case WHITE_VALUE: return WHITE;
      case GRAY_VALUE: return GRAY;
      case BLUE_VALUE: return BLUE;
      case GREEN_VALUE: return GREEN;
      case YELLOW_VALUE: return YELLOW;
      case CYAN_VALUE: return CYAN;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private WindowColor(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //WindowColor
