/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.ui.contentassist;

import xtext.qactor.ui.contentassist.AbstractQADockerProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class QADockerProposalProvider extends AbstractQADockerProposalProvider {
}
