/*
 * generated by Xtext 2.10.0
 */
package xtext.qactor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQADockerScopeProvider extends DelegatingScopeProvider {
}
