/*
 * generated by Xtext 2.10.0
 */
package xtext.qactor.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import xtext.qactor.qADocker.QActorSystem

@RunWith(XtextRunner)
@InjectWith(QADockerInjectorProvider)
class QADockerParsingTest{

	@Inject
	ParseHelper<QActorSystem> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
