/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor;

import xtext.qactor.QADockerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QADockerStandaloneSetup extends QADockerStandaloneSetupGenerated {
  public static void doSetup() {
    QADockerStandaloneSetup _qADockerStandaloneSetup = new QADockerStandaloneSetup();
    _qADockerStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
