/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.qactor.qADocker.MemoEvent;
import xtext.qactor.qADocker.QADockerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Memo Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MemoEventImpl extends MemoRuleImpl implements MemoEvent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MemoEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.MEMO_EVENT;
  }

} //MemoEventImpl
