/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.qactor.qADocker.MoveFile;
import xtext.qactor.qADocker.QADockerPackage;
import xtext.qactor.qADocker.VarOrString;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.impl.MoveFileImpl#getFname <em>Fname</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MoveFileImpl extends MinimalEObjectImpl.Container implements MoveFile
{
  /**
   * The cached value of the '{@link #getFname() <em>Fname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFname()
   * @generated
   * @ordered
   */
  protected VarOrString fname;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.MOVE_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarOrString getFname()
  {
    return fname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFname(VarOrString newFname, NotificationChain msgs)
  {
    VarOrString oldFname = fname;
    fname = newFname;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.MOVE_FILE__FNAME, oldFname, newFname);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFname(VarOrString newFname)
  {
    if (newFname != fname)
    {
      NotificationChain msgs = null;
      if (fname != null)
        msgs = ((InternalEObject)fname).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.MOVE_FILE__FNAME, null, msgs);
      if (newFname != null)
        msgs = ((InternalEObject)newFname).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.MOVE_FILE__FNAME, null, msgs);
      msgs = basicSetFname(newFname, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.MOVE_FILE__FNAME, newFname, newFname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QADockerPackage.MOVE_FILE__FNAME:
        return basicSetFname(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QADockerPackage.MOVE_FILE__FNAME:
        return getFname();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QADockerPackage.MOVE_FILE__FNAME:
        setFname((VarOrString)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.MOVE_FILE__FNAME:
        setFname((VarOrString)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.MOVE_FILE__FNAME:
        return fname != null;
    }
    return super.eIsSet(featureID);
  }

} //MoveFileImpl
