/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.qactor.qADocker.PAtomCut;
import xtext.qactor.qADocker.QADockerPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PAtom Cut</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PAtomCutImpl extends PPredefImpl implements PAtomCut
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PAtomCutImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.PATOM_CUT;
  }

} //PAtomCutImpl
