/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtext.qactor.qADocker.PAtomNum;
import xtext.qactor.qADocker.PIs;
import xtext.qactor.qADocker.QADockerPackage;
import xtext.qactor.qADocker.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PIs</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.impl.PIsImpl#getVarout <em>Varout</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.impl.PIsImpl#getVarin <em>Varin</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.impl.PIsImpl#getNum <em>Num</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PIsImpl extends PPredefImpl implements PIs
{
  /**
   * The cached value of the '{@link #getVarout() <em>Varout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarout()
   * @generated
   * @ordered
   */
  protected Variable varout;

  /**
   * The cached value of the '{@link #getVarin() <em>Varin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarin()
   * @generated
   * @ordered
   */
  protected Variable varin;

  /**
   * The cached value of the '{@link #getNum() <em>Num</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNum()
   * @generated
   * @ordered
   */
  protected PAtomNum num;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PIsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.PIS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getVarout()
  {
    return varout;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarout(Variable newVarout, NotificationChain msgs)
  {
    Variable oldVarout = varout;
    varout = newVarout;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__VAROUT, oldVarout, newVarout);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVarout(Variable newVarout)
  {
    if (newVarout != varout)
    {
      NotificationChain msgs = null;
      if (varout != null)
        msgs = ((InternalEObject)varout).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__VAROUT, null, msgs);
      if (newVarout != null)
        msgs = ((InternalEObject)newVarout).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__VAROUT, null, msgs);
      msgs = basicSetVarout(newVarout, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__VAROUT, newVarout, newVarout));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getVarin()
  {
    return varin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarin(Variable newVarin, NotificationChain msgs)
  {
    Variable oldVarin = varin;
    varin = newVarin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__VARIN, oldVarin, newVarin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVarin(Variable newVarin)
  {
    if (newVarin != varin)
    {
      NotificationChain msgs = null;
      if (varin != null)
        msgs = ((InternalEObject)varin).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__VARIN, null, msgs);
      if (newVarin != null)
        msgs = ((InternalEObject)newVarin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__VARIN, null, msgs);
      msgs = basicSetVarin(newVarin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__VARIN, newVarin, newVarin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PAtomNum getNum()
  {
    return num;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNum(PAtomNum newNum, NotificationChain msgs)
  {
    PAtomNum oldNum = num;
    num = newNum;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__NUM, oldNum, newNum);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNum(PAtomNum newNum)
  {
    if (newNum != num)
    {
      NotificationChain msgs = null;
      if (num != null)
        msgs = ((InternalEObject)num).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__NUM, null, msgs);
      if (newNum != null)
        msgs = ((InternalEObject)newNum).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.PIS__NUM, null, msgs);
      msgs = basicSetNum(newNum, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.PIS__NUM, newNum, newNum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QADockerPackage.PIS__VAROUT:
        return basicSetVarout(null, msgs);
      case QADockerPackage.PIS__VARIN:
        return basicSetVarin(null, msgs);
      case QADockerPackage.PIS__NUM:
        return basicSetNum(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QADockerPackage.PIS__VAROUT:
        return getVarout();
      case QADockerPackage.PIS__VARIN:
        return getVarin();
      case QADockerPackage.PIS__NUM:
        return getNum();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QADockerPackage.PIS__VAROUT:
        setVarout((Variable)newValue);
        return;
      case QADockerPackage.PIS__VARIN:
        setVarin((Variable)newValue);
        return;
      case QADockerPackage.PIS__NUM:
        setNum((PAtomNum)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.PIS__VAROUT:
        setVarout((Variable)null);
        return;
      case QADockerPackage.PIS__VARIN:
        setVarin((Variable)null);
        return;
      case QADockerPackage.PIS__NUM:
        setNum((PAtomNum)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.PIS__VAROUT:
        return varout != null;
      case QADockerPackage.PIS__VARIN:
        return varin != null;
      case QADockerPackage.PIS__NUM:
        return num != null;
    }
    return super.eIsSet(featureID);
  }

} //PIsImpl
