/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.qactor.qADocker.QADockerPackage;
import xtext.qactor.qADocker.RemoveRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Remove Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RemoveRuleImpl extends GuardMoveImpl implements RemoveRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RemoveRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.REMOVE_RULE;
  }

} //RemoveRuleImpl
