/**
 * generated by Xtext 2.10.0
 */
package xtext.qactor.qADocker.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.qactor.qADocker.PAtomic;
import xtext.qactor.qADocker.PStruct;
import xtext.qactor.qADocker.QADockerPackage;
import xtext.qactor.qADocker.VarOrAtomOrPStruct;
import xtext.qactor.qADocker.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Or Atom Or PStruct</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.qactor.qADocker.impl.VarOrAtomOrPStructImpl#getVar <em>Var</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.impl.VarOrAtomOrPStructImpl#getPsrtuct <em>Psrtuct</em>}</li>
 *   <li>{@link xtext.qactor.qADocker.impl.VarOrAtomOrPStructImpl#getAtom <em>Atom</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VarOrAtomOrPStructImpl extends MinimalEObjectImpl.Container implements VarOrAtomOrPStruct
{
  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected Variable var;

  /**
   * The cached value of the '{@link #getPsrtuct() <em>Psrtuct</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPsrtuct()
   * @generated
   * @ordered
   */
  protected PStruct psrtuct;

  /**
   * The cached value of the '{@link #getAtom() <em>Atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtom()
   * @generated
   * @ordered
   */
  protected PAtomic atom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarOrAtomOrPStructImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QADockerPackage.Literals.VAR_OR_ATOM_OR_PSTRUCT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVar(Variable newVar, NotificationChain msgs)
  {
    Variable oldVar = var;
    var = newVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR, oldVar, newVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar(Variable newVar)
  {
    if (newVar != var)
    {
      NotificationChain msgs = null;
      if (var != null)
        msgs = ((InternalEObject)var).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR, null, msgs);
      if (newVar != null)
        msgs = ((InternalEObject)newVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR, null, msgs);
      msgs = basicSetVar(newVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR, newVar, newVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PStruct getPsrtuct()
  {
    return psrtuct;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPsrtuct(PStruct newPsrtuct, NotificationChain msgs)
  {
    PStruct oldPsrtuct = psrtuct;
    psrtuct = newPsrtuct;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT, oldPsrtuct, newPsrtuct);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPsrtuct(PStruct newPsrtuct)
  {
    if (newPsrtuct != psrtuct)
    {
      NotificationChain msgs = null;
      if (psrtuct != null)
        msgs = ((InternalEObject)psrtuct).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT, null, msgs);
      if (newPsrtuct != null)
        msgs = ((InternalEObject)newPsrtuct).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT, null, msgs);
      msgs = basicSetPsrtuct(newPsrtuct, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT, newPsrtuct, newPsrtuct));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PAtomic getAtom()
  {
    return atom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtom(PAtomic newAtom, NotificationChain msgs)
  {
    PAtomic oldAtom = atom;
    atom = newAtom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM, oldAtom, newAtom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtom(PAtomic newAtom)
  {
    if (newAtom != atom)
    {
      NotificationChain msgs = null;
      if (atom != null)
        msgs = ((InternalEObject)atom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM, null, msgs);
      if (newAtom != null)
        msgs = ((InternalEObject)newAtom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM, null, msgs);
      msgs = basicSetAtom(newAtom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM, newAtom, newAtom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR:
        return basicSetVar(null, msgs);
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT:
        return basicSetPsrtuct(null, msgs);
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM:
        return basicSetAtom(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR:
        return getVar();
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT:
        return getPsrtuct();
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM:
        return getAtom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR:
        setVar((Variable)newValue);
        return;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT:
        setPsrtuct((PStruct)newValue);
        return;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM:
        setAtom((PAtomic)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR:
        setVar((Variable)null);
        return;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT:
        setPsrtuct((PStruct)null);
        return;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM:
        setAtom((PAtomic)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__VAR:
        return var != null;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__PSRTUCT:
        return psrtuct != null;
      case QADockerPackage.VAR_OR_ATOM_OR_PSTRUCT__ATOM:
        return atom != null;
    }
    return super.eIsSet(featureID);
  }

} //VarOrAtomOrPStructImpl
